import {
  LayoutDashboard,
  Users,
  Calendar,
  Stethoscope,
  Bed,
  AlertTriangle,
  UserCheck,
  Heart,
  TestTube,
  Scan,
  Pill,
  Package,
  Droplet,
  Scissors,
  Ambulance,
  Receipt,
  Shield,
  DollarSign,
  Briefcase,
  UserPlus,
  Building,
  BarChart3,
  LineChart,
  Settings,
  Lock,
  Bot,
  Cog,
} from "lucide-react";

export const sidebarMenuConfig = [
  {
    id: "dashboard",
    label: "Dashboard",
    icon: LayoutDashboard,
    path: "/",
    children: [
      { label: "Executive", path: "/" },
      { label: "Clinical", path: "/dashboard/clinical" },
      { label: "Finance", path: "/dashboard/finance" },
      { label: "Operational", path: "/dashboard/operational" },
      { label: "Analytics", path: "/dashboard/analytics" },
    ],
  },
  {
    id: "patients",
    label: "Patient Management",
    icon: Users,
    path: "/patients",
    children: [
      { label: "All Patients", path: "/patients" },
      { label: "Registration", path: "/patients/register" },
      { label: "Medical History", path: "/patients/medical-history" },
      { label: "Allergies", path: "/patients/allergies" },
      { label: "Insurance", path: "/patients/insurance" },
      { label: "Documents", path: "/patients/documents" },
    ],
  },
  {
    id: "appointments",
    label: "Appointments",
    icon: Calendar,
    path: "/appointments",
    children: [
      { label: "All Appointments", path: "/appointments" },
      { label: "Calendar", path: "/appointments/calendar" },
      { label: "Doctor Schedule", path: "/appointments/schedule" },
      { label: "Queue Management", path: "/appointments/queue" },
      { label: "Telemedicine", path: "/appointments/telemedicine" },
    ],
  },
  {
    id: "opd",
    label: "OPD",
    icon: Stethoscope,
    path: "/opd",
    children: [
      { label: "Visits", path: "/opd" },
      { label: "Consultation", path: "/opd/consultation" },
      { label: "Prescription", path: "/opd/prescription" },
      { label: "Diagnosis", path: "/opd/diagnosis" },
      { label: "Clinical Notes", path: "/opd/notes" },
      { label: "Billing", path: "/opd/billing" },
    ],
  },
  {
    id: "ipd",
    label: "IPD",
    icon: Bed,
    path: "/ipd",
    children: [
      { label: "Admissions", path: "/ipd" },
      { label: "Bed Allocation", path: "/ipd/beds" },
      { label: "Ward Management", path: "/ipd/wards" },
      { label: "Nursing Chart", path: "/ipd/nursing-chart" },
      { label: "Discharge", path: "/ipd/discharge" },
      { label: "Discharge Summary", path: "/ipd/discharge-summary" },
    ],
  },
  {
    id: "emergency",
    label: "Emergency",
    icon: AlertTriangle,
    path: "/emergency",
    children: [
      { label: "Patients", path: "/emergency" },
      { label: "Triage", path: "/emergency/triage" },
      { label: "Queue", path: "/emergency/queue" },
      { label: "Billing", path: "/emergency/billing" },
    ],
  },
  {
    id: "doctors",
    label: "Doctors",
    icon: UserCheck,
    path: "/doctors",
    children: [
      { label: "All Doctors", path: "/doctors" },
      { label: "Availability", path: "/doctors/availability" },
      { label: "Leaves", path: "/doctors/leaves" },
      { label: "Departments", path: "/doctors/departments" },
      { label: "Specializations", path: "/doctors/specializations" },
    ],
  },
  {
    id: "nurse",
    label: "Nurse Station",
    icon: Heart,
    path: "/nurse",
    children: [
      { label: "Assigned Patients", path: "/nurse" },
      { label: "Medication", path: "/nurse/medication" },
      { label: "Vitals", path: "/nurse/vitals" },
      { label: "Nursing Notes", path: "/nurse/notes" },
      { label: "Shift Handover", path: "/nurse/shift" },
    ],
  },
  {
    id: "laboratory",
    label: "Laboratory",
    icon: TestTube,
    path: "/lab",
    children: [
      { label: "Lab Orders", path: "/lab" },
      { label: "Sample Collection", path: "/lab/samples" },
      { label: "Processing", path: "/lab/processing" },
      { label: "Reports", path: "/lab/reports" },
      { label: "Templates", path: "/lab/templates" },
      { label: "Reference Values", path: "/lab/reference" },
    ],
  },
  {
    id: "radiology",
    label: "Radiology",
    icon: Scan,
    path: "/radiology",
    children: [
      { label: "Orders", path: "/radiology" },
      { label: "Imaging", path: "/radiology/imaging" },
      { label: "Reports", path: "/radiology/reports" },
    ],
  },
  {
    id: "pharmacy",
    label: "Pharmacy",
    icon: Pill,
    path: "/pharmacy",
    children: [
      { label: "Medicines", path: "/pharmacy" },
      { label: "Inventory", path: "/pharmacy/inventory" },
      { label: "Purchase", path: "/pharmacy/purchase" },
      { label: "Sales", path: "/pharmacy/sales" },
      { label: "Expiry", path: "/pharmacy/expiry" },
      { label: "Suppliers", path: "/pharmacy/suppliers" },
    ],
  },
  {
    id: "inventory",
    label: "Inventory",
    icon: Package,
    path: "/inventory",
    children: [
      { label: "Products", path: "/inventory" },
      { label: "Stock", path: "/inventory/stock" },
      { label: "Purchase Orders", path: "/inventory/purchase-orders" },
      { label: "GRN", path: "/inventory/grn" },
      { label: "Vendors", path: "/inventory/vendors" },
      { label: "Assets", path: "/inventory/assets" },
    ],
  },
  {
    id: "blood-bank",
    label: "Blood Bank",
    icon: Droplet,
    path: "/blood-bank",
    children: [
      { label: "Donors", path: "/blood-bank" },
      { label: "Blood Stock", path: "/blood-bank/stock" },
      { label: "Issue Blood", path: "/blood-bank/issue" },
      { label: "Compatibility", path: "/blood-bank/compatibility" },
    ],
  },
  {
    id: "ot",
    label: "Operation Theatre",
    icon: Scissors,
    path: "/ot",
    children: [
      { label: "OT Schedule", path: "/ot" },
      { label: "Operation List", path: "/ot/operations" },
      { label: "Surgeons", path: "/ot/surgeons" },
      { label: "Operation Notes", path: "/ot/notes" },
    ],
  },
  {
    id: "ambulance",
    label: "Ambulance",
    icon: Ambulance,
    path: "/ambulance",
    children: [
      { label: "Vehicles", path: "/ambulance" },
      { label: "Drivers", path: "/ambulance/drivers" },
      { label: "Bookings", path: "/ambulance/bookings" },
      { label: "Maintenance", path: "/ambulance/maintenance" },
    ],
  },
  {
    id: "billing",
    label: "Billing",
    icon: Receipt,
    path: "/billing",
    children: [
      { label: "Invoices", path: "/billing" },
      { label: "Payments", path: "/billing/payments" },
      { label: "Refunds", path: "/billing/refunds" },
      { label: "Packages", path: "/billing/packages" },
      { label: "Services", path: "/billing/services" },
      { label: "Taxes", path: "/billing/taxes" },
    ],
  },
  {
    id: "insurance",
    label: "Insurance",
    icon: Shield,
    path: "/insurance",
    children: [
      { label: "Claims", path: "/insurance" },
      { label: "Companies", path: "/insurance/companies" },
      { label: "Policies", path: "/insurance/policies" },
      { label: "Approvals", path: "/insurance/approvals" },
    ],
  },
  {
    id: "finance",
    label: "Finance",
    icon: DollarSign,
    path: "/finance",
    children: [
      { label: "Income", path: "/finance" },
      { label: "Expense", path: "/finance/expense" },
      { label: "Ledger", path: "/finance/ledger" },
      { label: "Bank", path: "/finance/bank" },
      { label: "Budget", path: "/finance/budget" },
      { label: "Profit & Loss", path: "/finance/profit-loss" },
    ],
  },
  {
    id: "hr",
    label: "HR",
    icon: Briefcase,
    path: "/hr",
    children: [
      { label: "Employees", path: "/hr" },
      { label: "Attendance", path: "/hr/attendance" },
      { label: "Leaves", path: "/hr/leaves" },
      { label: "Payroll", path: "/hr/payroll" },
      { label: "Shift", path: "/hr/shift" },
      { label: "Recruitment", path: "/hr/recruitment" },
    ],
  },
  {
    id: "crm",
    label: "CRM",
    icon: UserPlus,
    path: "/crm",
    children: [
      { label: "Leads", path: "/crm" },
      { label: "Communication", path: "/crm/communication" },
      { label: "Campaign", path: "/crm/campaign" },
      { label: "Feedback", path: "/crm/feedback" },
    ],
  },
  {
    id: "front-office",
    label: "Front Office",
    icon: Building,
    path: "/front-office",
    children: [
      { label: "Visitors", path: "/front-office" },
      { label: "Reception", path: "/front-office/reception" },
      { label: "Phone Calls", path: "/front-office/calls" },
      { label: "Complaints", path: "/front-office/complaints" },
    ],
  },
  {
    id: "reports",
    label: "Reports",
    icon: BarChart3,
    path: "/reports",
    children: [
      { label: "Clinical Reports", path: "/reports" },
      { label: "Financial Reports", path: "/reports/financial" },
      { label: "Lab Reports", path: "/reports/lab" },
      { label: "Inventory Reports", path: "/reports/inventory" },
      { label: "Audit Reports", path: "/reports/audit" },
      { label: "Custom Reports", path: "/reports/custom" },
    ],
  },
  {
    id: "analytics",
    label: "Analytics",
    icon: LineChart,
    path: "/analytics",
    children: [
      { label: "KPIs", path: "/analytics" },
      { label: "Revenue", path: "/analytics/revenue" },
      { label: "Patients", path: "/analytics/patients" },
      { label: "Doctors", path: "/analytics/doctors" },
      { label: "Departments", path: "/analytics/departments" },
    ],
  },
  {
    id: "administration",
    label: "Administration",
    icon: Settings,
    path: "/admin",
    children: [
      { label: "Hospital Settings", path: "/admin" },
      { label: "Departments", path: "/admin/departments" },
      { label: "Branches", path: "/admin/branches" },
      { label: "Rooms & Beds", path: "/admin/rooms" },
      { label: "Services", path: "/admin/services" },
      { label: "Audit Logs", path: "/admin/audit" },
      { label: "System Logs", path: "/admin/logs" },
      { label: "API Keys", path: "/admin/api-keys" },
    ],
  },
  {
    id: "user-management",
    label: "User Management",
    icon: Lock,
    path: "/users",
    children: [
      { label: "Users", path: "/users" },
      { label: "Roles", path: "/users/roles" },
      { label: "Permissions", path: "/users/permissions" },
      { label: "Role Matrix", path: "/users/role-matrix" },
      { label: "Login History", path: "/users/login-history" },
    ],
  },
  {
    id: "ai",
    label: "AI Center",
    icon: Bot,
    path: "/ai",
    children: [
      { label: "AI Assistant", path: "/ai" },
      { label: "Medical Scribe", path: "/ai/scribe" },
      { label: "AI Diagnosis", path: "/ai/diagnosis" },
      { label: "Document AI", path: "/ai/documents" },
      { label: "Voice AI", path: "/ai/voice" },
    ],
  },
  {
    id: "settings",
    label: "Settings",
    icon: Cog,
    path: "/settings",
    children: [
      { label: "General", path: "/settings" },
      { label: "Branding", path: "/settings/branding" },
      { label: "Security", path: "/settings/security" },
      { label: "Localization", path: "/settings/localization" },
      { label: "Backup", path: "/settings/backup" },
      { label: "Notifications", path: "/settings/notifications" },
      { label: "Integrations", path: "/settings/integrations" },
    ],
  },
];
