// Define all possible permissions
export const PERMISSIONS = {
  DASHBOARD_VIEW: 'DASHBOARD_VIEW',
  PATIENTS_VIEW: 'PATIENTS_VIEW',
  PATIENTS_CREATE: 'PATIENTS_CREATE',
  PATIENTS_EDIT: 'PATIENTS_EDIT',
  APPOINTMENTS_VIEW: 'APPOINTMENTS_VIEW',
  APPOINTMENTS_CREATE: 'APPOINTMENTS_CREATE',
  OPD_VIEW: 'OPD_VIEW',
  IPD_VIEW: 'IPD_VIEW',
  EMERGENCY_VIEW: 'EMERGENCY_VIEW',
  NURSE_STATION_VIEW: 'NURSE_STATION_VIEW',
  LABORATORY_VIEW: 'LABORATORY_VIEW',
  PHARMACY_VIEW: 'PHARMACY_VIEW',
  INVENTORY_VIEW: 'INVENTORY_VIEW',
  SETTINGS_VIEW: 'SETTINGS_VIEW',
};

// Define roles and their associated permissions
export const ROLES = {
  SUPER_ADMIN: Object.values(PERMISSIONS),
  DOCTOR: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.PATIENTS_VIEW,
    PERMISSIONS.APPOINTMENTS_VIEW,
    PERMISSIONS.OPD_VIEW,
    PERMISSIONS.IPD_VIEW,
    PERMISSIONS.EMERGENCY_VIEW,
    PERMISSIONS.LABORATORY_VIEW,
  ],
  NURSE: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.PATIENTS_VIEW,
    PERMISSIONS.IPD_VIEW,
    PERMISSIONS.NURSE_STATION_VIEW,
  ],
  RECEPTIONIST: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.PATIENTS_VIEW,
    PERMISSIONS.PATIENTS_CREATE,
    PERMISSIONS.APPOINTMENTS_VIEW,
    PERMISSIONS.APPOINTMENTS_CREATE,
  ]
};

// Helper to check if a role has a specific permission
export const hasPermission = (role, permission) => {
  const rolePermissions = ROLES[role] || [];
  return rolePermissions.includes(permission);
};
