// Define all possible permissions
export const PERMISSIONS = {
  DASHBOARD_VIEW: 'DASHBOARD_VIEW',
  PATIENTS_VIEW: 'PATIENTS_VIEW',
  PATIENTS_CREATE: 'PATIENTS_CREATE',
  PATIENTS_EDIT: 'PATIENTS_EDIT',
  APPOINTMENTS_VIEW: 'APPOINTMENTS_VIEW',
  APPOINTMENTS_CREATE: 'APPOINTMENTS_CREATE',
  OPD_VIEW: 'OPD_VIEW',
  IPD_VIEW: 'IPD_VIEW',
  EMERGENCY_VIEW: 'EMERGENCY_VIEW',
  NURSE_STATION_VIEW: 'NURSE_STATION_VIEW',
  LABORATORY_VIEW: 'LABORATORY_VIEW',
  PHARMACY_VIEW: 'PHARMACY_VIEW',
  INVENTORY_VIEW: 'INVENTORY_VIEW',
  SETTINGS_VIEW: 'SETTINGS_VIEW',
  
  // Doctor Portal Specific Permissions
  APPOINTMENT_VIEW: 'Appointment.View',
  APPOINTMENT_UPDATE: 'Appointment.Update',
  PATIENT_VIEW: 'Patient.View',
  CLINICALNOTE_CREATE: 'ClinicalNote.Create',
  CLINICALNOTE_UPDATE: 'ClinicalNote.Update',
  PRESCRIPTION_CREATE: 'Prescription.Create',
  PRESCRIPTION_UPDATE: 'Prescription.Update',
  LABORDER_CREATE: 'LabOrder.Create',
  RADIOLOGYORDER_CREATE: 'RadiologyOrder.Create',
  REPORT_VIEW: 'Report.View',
  TELEMEDICINE_JOIN: 'Telemedicine.Join',
  CALENDAR_VIEW: 'Calendar.View',
  DOCUMENT_UPLOAD: 'Document.Upload',
  PROFILE_UPDATE: 'Profile.Update',
};

// Define roles and their associated permissions
export const ROLES = {
  SUPER_ADMIN: Object.values(PERMISSIONS),
  DOCTOR: [
    PERMISSIONS.APPOINTMENT_VIEW,
    PERMISSIONS.APPOINTMENT_UPDATE,
    PERMISSIONS.PATIENT_VIEW,
    PERMISSIONS.CLINICALNOTE_CREATE,
    PERMISSIONS.CLINICALNOTE_UPDATE,
    PERMISSIONS.PRESCRIPTION_CREATE,
    PERMISSIONS.PRESCRIPTION_UPDATE,
    PERMISSIONS.LABORDER_CREATE,
    PERMISSIONS.RADIOLOGYORDER_CREATE,
    PERMISSIONS.REPORT_VIEW,
    PERMISSIONS.TELEMEDICINE_JOIN,
    PERMISSIONS.CALENDAR_VIEW,
    PERMISSIONS.DOCUMENT_UPLOAD,
    PERMISSIONS.PROFILE_UPDATE,
  ],
  NURSE: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.PATIENTS_VIEW,
    PERMISSIONS.IPD_VIEW,
    PERMISSIONS.NURSE_STATION_VIEW,
  ],
  RECEPTIONIST: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.PATIENTS_VIEW,
    PERMISSIONS.PATIENTS_CREATE,
    PERMISSIONS.APPOINTMENTS_VIEW,
    PERMISSIONS.APPOINTMENTS_CREATE,
  ]
};

// Helper to check if a role has a specific permission
export const hasPermission = (role, permission) => {
  const rolePermissions = ROLES[role] || [];
  return rolePermissions.includes(permission);
};
